/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekuts;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import projekuts.Transaksi.itemTransaksi;


/**
 *
 * @author M IQBAL
 */
public class FormPembayaran extends javax.swing.JFrame {

    ArrayList<Barang> daftarBarang;
    ArrayList<Transaksi> newTransaksi = new ArrayList<>();
    TableModel daftarModel;
    int jumlahBelanja = 0;

    
    public FormPembayaran() {
       
        DBConnector.initDBConnection();
        Barang.loadBarangFromDB();
        System.out.println(Barang.daftarBarang.size());
        daftarBarang = Barang.daftarBarang;
        System.out.println(daftarBarang.size());
        initComponents();
        generalID();
        
        Timer timer = new Timer(1000, e -> {
            updateTime();
        });
        timer.start();
        
        daftarModel = daftarTable.getModel();
        
        daftarModel.addTableModelListener(new TableModelListener()
                {
            @Override
            public void tableChanged(TableModelEvent e) {
           
            System.out.println("Table Changed");
            
            if(e.getColumn()==5){
                 float total;
                 float totalBelanja=0.0f;
                
               for(int i=0;i<jumlahBelanja;i++){
                    total = (float)daftarModel.getValueAt(i, 5);
                    totalBelanja = totalBelanja+total;
               } 
               int totalBelanjaInt = (int)totalBelanja;
               total_harga.setText(String.format("%,d",totalBelanjaInt));
            }
                  
                
            }
                    
                }
        
        );
    }

private void generalID(){
        try {
            Statement stmt = DBConnector.connection.createStatement();
            String sql = "SELECT COUNT(*) as jumlah_transaksi FROM sum_transaksi";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            int JumlahData = rs.getInt("jumlah_transaksi");
            System.out.println(JumlahData);
            int GeneralID = JumlahData+1;
            String idTransString = String.format("TR%03d", GeneralID);

            id_transaksi.setText(idTransString);            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
              
        }
    
    
}
    
private void updateTime() {
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String formattedDate = now.format(formatter);
        tgl_field.setText(formattedDate);
    }




                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_barang = new javax.swing.JTextField();
        harga_barang = new javax.swing.JTextField();
        jlh_pesanan = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        total_harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uang_diterima = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tgl_field = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        jLabel1.setText("Nomor Transaksi");

        id_transaksi.setEditable(false);
        id_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        id_transaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N
        jLabel3.setText("ID Barang");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N
        jLabel4.setText("Harga Satuan");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N
        jLabel5.setText("Jumlah Pesanan");

        id_barang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barangActionPerformed(evt);
            }
        });

        harga_barang.setEditable(false);
        harga_barang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlh_pesanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlh_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlh_pesananActionPerformed(evt);
            }
        });

        nama_barang.setEditable(false);
        nama_barang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        total_harga.setEditable(false);
        total_harga.setBackground(new java.awt.Color(153, 153, 255));
        total_harga.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        total_harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N
        jLabel6.setText("Uang Diterima");

        uang_diterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uang_diterimaActionPerformed(evt);
            }
        });
        uang_diterima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uang_diterimaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N
        jLabel7.setText("Kembalian");

        kembalian.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        jLabel8.setText("Tanggal dan Waktu");

        tgl_field.setEditable(false);
        tgl_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tgl_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_save.setText("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        daftarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Barang", "Nama Barang", "Harga Barang", "Jumlah Pesanan", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(daftarTable);
        if (daftarTable.getColumnModel().getColumnCount() > 0) {
            daftarTable.getColumnModel().getColumn(0).setResizable(false);
            daftarTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(1).setResizable(false);
            daftarTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            daftarTable.getColumnModel().getColumn(2).setResizable(false);
            daftarTable.getColumnModel().getColumn(2).setPreferredWidth(300);
            daftarTable.getColumnModel().getColumn(3).setResizable(false);
            daftarTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            daftarTable.getColumnModel().getColumn(4).setResizable(false);
            daftarTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            daftarTable.getColumnModel().getColumn(5).setResizable(false);
            daftarTable.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel2)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(harga_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlh_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)))
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(tgl_field, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uang_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlh_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tgl_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(total_harga)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(uang_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barangActionPerformed
       String kodeInput = id_barang.getText();
       Barang tempBarang;
       boolean ditemukan = false;
       
       for(int i = 0; i< daftarBarang.size(); i++){
            tempBarang = daftarBarang.get(i); 
            if(tempBarang.id_barang.equals(kodeInput)){     
                System.out.println("Barang Ditemukan");
                nama_barang.setText(tempBarang.nama);
                harga_barang.setText(Float.toString(tempBarang.harga));
                jlh_pesanan.setText("1");
                ditemukan = true;
            }
         
        }
       
       if(!ditemukan){
           JOptionPane.showMessageDialog(this, "Barang dengan ID yang diinputkan tidak ditemukan", "ERROR ID", JOptionPane.ERROR_MESSAGE);
           id_barang.setText("");
           nama_barang.setText("");
           harga_barang.setText("");
       }
       
       
    }//GEN-LAST:event_id_barangActionPerformed

    private void jlh_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlh_pesananActionPerformed
        String jlhPesanan = jlh_pesanan.getText();
        String kodeInput = id_barang.getText();
        int tempIndex = 0;
        
        Barang tempBarang;
        
        if(Character.isDigit(jlhPesanan.charAt(0))){
           for(int i = 0; i< daftarBarang.size(); i++){
                tempBarang = daftarBarang.get(i);
                if(tempBarang.id_barang.equals(kodeInput)){
                    tempIndex = jumlahBelanja;
                    jumlahBelanja++;

                       daftarModel.setValueAt(jumlahBelanja, tempIndex, 0);
                       daftarModel.setValueAt(kodeInput, tempIndex, 1);
                       daftarModel.setValueAt(tempBarang.nama, tempIndex, 2);
                       daftarModel.setValueAt(tempBarang.harga, tempIndex, 3);
                       daftarModel.setValueAt(jlhPesanan, tempIndex, 4);

                       float totalBelanja = (float)tempBarang.harga*Integer.parseInt(jlhPesanan);
                       daftarModel.setValueAt(totalBelanja,tempIndex,5);
                } 
            }  
        } else {
            JOptionPane.showMessageDialog(this, "Anda Memasukkan huruf, Silakan Memasukkan angka","INPUT ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
       
        
        id_barang.setText("");
        nama_barang.setText("");
        harga_barang.setText("");
        jlh_pesanan.setText("");
        
    }//GEN-LAST:event_jlh_pesananActionPerformed

    private void uang_diterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uang_diterimaActionPerformed
       String totalbelanja = total_harga.getText();
       String stringTotalBelanja = totalbelanja.replace(",", "");
       
       float totalBelanja = Float.parseFloat(stringTotalBelanja);
       int totalBelanjaInt = (int)totalBelanja;

       String bayar = uang_diterima.getText();
       String stringBayar = bayar.replace(",", "");

       float dibayar = Float.parseFloat(stringBayar);
       int dibayarInt = (int)dibayar;

       int uang_kembali = dibayarInt - totalBelanjaInt;
       if(dibayar >= totalBelanjaInt){
            kembalian.setText(String.format("%,d",uang_kembali));
       } else {
            JOptionPane.showMessageDialog(this, "Uang Anda Kurang","ERROR MONEY",JOptionPane.ERROR_MESSAGE);
            uang_diterima.setText("");
        }
       
        
          
        
    }//GEN-LAST:event_uang_diterimaActionPerformed

    private void uang_diterimaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uang_diterimaKeyReleased
       
        
        String dibayarString = uang_diterima.getText();
        if(Character.isDigit(dibayarString.charAt(0))){
            dibayarString = dibayarString.replace(",","");
            int dibayarInput = Integer.parseInt(dibayarString);
            uang_diterima.setText(String.format("%,d",dibayarInput));
       } else {
           JOptionPane.showMessageDialog(this, "Anda Memasukkan huruf, Silakan Memasukkan angka","INPUT ERROR", JOptionPane.ERROR_MESSAGE);
           uang_diterima.setText("");
       }
        
    }//GEN-LAST:event_uang_diterimaKeyReleased

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String idTransaksi = id_transaksi.getText();
        int intIDTransaksi = Integer.parseInt(idTransaksi.substring(2));
        
        
        String totalHarga = total_harga.getText();
        totalHarga =totalHarga.replace(",","");
        float floatTotalHarga = Float.parseFloat(totalHarga);
        
        String uang_dibayar = uang_diterima.getText();
        uang_dibayar = uang_dibayar.replace(",","");
        float floatUang_dibayar = Float.parseFloat(uang_dibayar);
        
        String kembalianString = kembalian.getText();
        kembalianString = kembalianString.replace(",","");
        float floatKembalian = Float.parseFloat(kembalianString);
        
        String date = tgl_field.getText();
        
        Transaksi transaksi = new Transaksi(intIDTransaksi,floatTotalHarga,floatUang_dibayar, floatKembalian, date);
        
        
        for(int i=0; i<jumlahBelanja;i++){
            String id_barang = daftarModel.getValueAt(i, 1).toString();
            String nama_barang = daftarModel.getValueAt(i,2).toString();
            float harga_satuan = Float.parseFloat(daftarModel.getValueAt(i,3).toString());
            int jumlah_barang = Integer.parseInt(daftarModel.getValueAt(i,4).toString());
            float harga_total = Float.parseFloat(daftarModel.getValueAt(i,5).toString());
            itemTransaksi item = new itemTransaksi(id_barang, nama_barang, harga_satuan, jumlah_barang, harga_total);
            transaksi.addItem(item);
          
            
        }
        
        newTransaksi.add(transaksi);
        try {
            Transaksi.simpanDatabase();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan Penyimpanan Ke Database","DATABASE ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
        new FormPembayaran().setVisible(true);
        generalID();
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JTable daftarTable;
    private javax.swing.JTextField harga_barang;
    private javax.swing.JTextField id_barang;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jlh_pesanan;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField tgl_field;
    private javax.swing.JTextField total_harga;
    private javax.swing.JTextField uang_diterima;
    // End of variables declaration//GEN-END:variables
}
